from stack import*
#primeiro criar pilha 'a'
#segundo criar pilha 'c'
#terceiro push para pilha 'a', para colocar o elemento na pilha'a'
#querto push(top pilha 'a', para pilha (c)
#quinto pop (a)

#exerc1
'''print("-----criar pilhas------")
a=new()
b=new()
c=new()
print("pilha A")
view(a)
print("pilha B")
view(b)
print("pilha C")
view (c)
print ("----------------------")
a=push(1,a)
print("pilha A")
view(a)
print ("----------------------")
c=push(top(a),c)
a=pop(a)
print("pilha A")
view(a)
print("pilha C")
view (c)
print ("----------------------")'''
 #-------------------------------------------
#exerc.2 -- dois elementos
print("-----criar pilhas------")
a=new()
b=new()
c=new()
print("pilha A")
view(a)
print("pilha B")
view (b)
print("pilha C")
view (c)
print ("---------alimentar pilhas-------------")
a=push(3,a)
a=push(2,a)
a=push(1,a)
print("pilha A")
view(a)
print ("---------LIFO de A para C-----1 PASSO--------")
c=push(top(a),c)
a=pop(a)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)

print ("-------LIFO de A para B-------2 PASSO--------")
b=push(top(a),b)
a=pop(a)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)

print ("--------LIFO de C para B------3PASSO--------")
b=push(top(c),b)
c=pop(c)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)
print ("-------LIFO de A para C------4 PASSO---------")
c=push(top(a),c)
a=pop(a)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)
print ("-------LIFO de B para A------5 PASSO---------")
a=push(top(b),a)
b=pop(b)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)
print ("-------LIFO de B para C------6PASSO---------")
c=push(top(b),c)
b=pop(b)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)
print ("-------LIFO de A para C-------7 PASSO--------")
c=push(top(a),c)
a=pop(a)
print("pilha A")
view(a)
print("pilha b")
view (b)
print("pilha C")
view (c)

